### ISSUE TITLE
from openea.approaches.transformer import transformer_model？

### ISSUE THREAD

**Issue by daima2017** [JadeXIN/IMEA#2]
https://github.com/JadeXIN/IMEA/blob/7d40b6b426f457055db2a00f3448eaf16bab8cd5/src/openea/approaches/transformer4ea_bce.py#L17

where is openea.approaches.transformer？
and where is transformer_model？？

**Comment by JadeXIN** [comment]
Thank you for finding this mistake. I will upload my missing file now.
