### ISSUE TITLE
failed to get dataset

### ISSUE THREAD

**Issue by frozenc** [JadeXIN/IMEA#3]
when i tried to get dataset from the link https://www.dropbox.com/s/hbyzesmz1u7ejdu/OpenEA_dataset.zip?dl=0
it appears some problem...
how can i get the dataset successfully?
![image](https://user-images.githubusercontent.com/27072350/155912043-6a59ae71-4d9c-4e4e-89b1-e8ca7bda979d.png)

**Comment by JadeXIN** [comment]
Thank you for your interest in our work. I guess it may be because you are in China mainland so you cannot utilize dropbox. You can contact the author of OpenEA directly.
