### ISSUE TITLE
Invalid dataset download link

### ISSUE THREAD

**Issue by kevinzhangcode** [JadeXIN/IMEA#4]
Hi，
Nice work ! I follow the dataset download link，but find that can't be downloaded.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/38588781/167080328-e34e42fa-e67c-4aff-ad6a-aac857a4f4b0.png">

**Comment by JadeXIN** [comment]
Thank you for your interest in our work. I guess it may be because you are in China mainland so you cannot utilize dropbox. You can contact the author of OpenEA directly.

**Comment by kevinzhangcode** [comment]
> author of OpenEA directly.

I had use a proxy to visit the link, but saw the same page .
Thanks! I have already get the data from [OpenEA](https://github.com/nju-websoft/OpenEA).

**Comment by JadeXIN** [comment]
that's great. if you have any other issues, pls feel free to post here.
