### ISSUE TITLE
Hello, can you provide a complete code? The code directory is still incomplete.

### ISSUE THREAD

**Issue by yangluheng** [JadeXIN/IMEA#5]
Hello, can you provide a complete code? The code directory is still incomplete.

**Comment by JadeXIN** [comment]
Hi, 
Thank you for your interest of our work. Could you specify which directory is incomplete? I only omit the datasets and specify the directory of the dataset. Maybe I lost some part of the implementation. can you tell me directly?

Best regards

**Comment by yangluheng** [comment]
Hello,

(1)
***@***.***

Can you please  provide the correct method of importing packages from this .py files?


(2) In addition, many packages imported by this file do not exist. Youcan see as follows:

***@***.***


(3) After I made some adjustments, I ran the code until the end of the 2 epoch, and there was a problem.

***@***.***


***@***.***


I wonder if you could spend your precious time answering my question.
Bset regards
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2022年7月19日 9:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [JadeXIN/IMEA] Hello, can you provide a complete code? The code directory is still incomplete. (Issue #5)


Hi,
Thank you for your interest of our work. Could you specify which directory is incomplete? I only omit the datasets and specify the directory of the dataset. Maybe I lost some part of the implementation. can you tell me directly?

Best regards

―

**Comment by JadeXIN** [comment]
Hi, your issue is encrypted, so i can only see ''*****@*******''. If possible, you can contact me via email: xkxjane@gmail.com
